[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
swap_v0 = "DGQDm3ApWihv9ugagD7SySKzdTpqdAEaW72mqR1xhzNp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "sasBM6wN3hGDJ6SDwgH9texQUHufQ5CWafPCbKJGH8X.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
